//go:build !ignore_autogenerated

package v1alpha1

import (
	"github.com/awslabs/operatorpkg/status"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *LXDNodeClass) DeepCopyInto(out *LXDNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *LXDNodeClass) DeepCopy() *LXDNodeClass {
	if in == nil {
		return nil
	}
	out := new(LXDNodeClass)
	in.DeepCopyInto(out)
	return out
}

func (in *LXDNodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LXDNodeClassList) DeepCopyInto(out *LXDNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LXDNodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *LXDNodeClassList) DeepCopy() *LXDNodeClassList {
	if in == nil {
		return nil
	}
	out := new(LXDNodeClassList)
	in.DeepCopyInto(out)
	return out
}

func (in *LXDNodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LXDNodeClassStatus) DeepCopyInto(out *LXDNodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]status.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *LXDNodeClassStatus) DeepCopy() *LXDNodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(LXDNodeClassStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *LXDNodeClassSpec) DeepCopyInto(out *LXDNodeClassSpec) {
	*out = *in
	out.NodeRegistrationDelay = in.NodeRegistrationDelay
}

func (in *LXDNodeClassSpec) DeepCopy() *LXDNodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(LXDNodeClassSpec)
	in.DeepCopyInto(out)
	return out
}
