apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k3s-lxd-provider.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k3s-lxd-provider.labels" . | nindent 4 }}
